-- 已废弃：组织架构与用户组织绑定由 Organizational-Service 维护。
-- 请使用 Organizational-Service/src/main/resources/db/org_schema.sql
-- MCP 小组 = sys_org_unit.type = 'GROUP'，成员/导师 = sys_user_org
-- Mentoring-Service 仅保留 mcp_student_ext、mcp_record、mcp_case、mcp_appointment_slot（见 mcp_schema_extension.sql）
